import type {CommanderProgress} from '@/lib/commander-progress';
type Destination='growth'|'heroes'|'drone'|'gear'|'reports';
type Props={name:string;power:string;powerRank:number|null;vs:string;vsNote:string;progress:CommanderProgress;onOpen:(tab:Destination)=>void};
export function CommanderHome({name,power,powerRank,vs,vsNote,progress,onOpen}:Props){
 const heroes=(progress.heroProfile.heroes as Array<{name?:string;level?:number}>|undefined)??[]; const namedHeroes=heroes.filter(h=>h.name).length;
 const droneLevel=Number(progress.droneProfile.level??0), boost=Number(progress.droneProfile.combatBoost??0); const gearHeroes=(progress.gearProfile.heroes as Array<{levels?:number[]}>|undefined)??[]; const gearEntered=gearHeroes.length>0;
 const profileAreas=[progress.updatedAt?1:0,namedHeroes?1:0,droneLevel?1:0,gearEntered?1:0].reduce((a,b)=>a+b,0);
 return <><section className="oopz-hero overflow-hidden rounded-[2rem] border border-[#5a2870] p-6 sm:p-8"><p className="text-xs font-black tracking-[.2em] text-[#ff74d4]">OOPZ COMMAND CENTER</p><div className="mt-3 grid gap-7 lg:grid-cols-[1.3fr_.7fr] lg:items-end"><div><h1 className="text-4xl font-black tracking-[-.05em] sm:text-5xl">Welcome back, {name}.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#c3b5ca]">Your complete growth briefing—from headquarters and heroes to drone, gear and this week’s alliance impact.</p></div><div className="rounded-2xl border border-white/10 bg-black/25 p-4"><div className="flex justify-between text-xs"><span className="text-[#b8a7c1]">Profile coverage</span><strong>{profileAreas}/4 labs</strong></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-black/40"><div className="h-full rounded-full bg-gradient-to-r from-[#8b5cf6] to-[#ff3cac]" style={{width:`${profileAreas/4*100}%`}}/></div></div></div></section>
 <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Account power" value={power} note={powerRank?`#${powerRank} in OOPZ`:'Link commander to rank'}/><Metric label="Weekly VS" value={vs} note={vsNote}/><Metric label="Headquarters" value={String(progress.hqLevel)} note={`${progress.workerCount} workers · ${progress.techCenterCount} tech centers`}/><Metric label="Main squad" value={`${namedHeroes}/5`} note={namedHeroes?'Heroes recorded':'Hero setup missing'}/></div>
 <section className="mt-6"><div className="flex items-end justify-between"><div><p className="text-xs font-black tracking-[.16em] text-[#ff62ce]">YOUR NEXT MOVES</p><h2 className="mt-2 text-2xl font-black">One briefing. Every system.</h2></div><span className="hidden text-xs text-[#8c7b96] sm:block">Tap a card for the full lab</span></div><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
  <Action title="Growth & buildings" status={`HQ ${progress.hqLevel} → ${Math.min(35,progress.hqLevel+1)}`} text={`Keep ${progress.vehicleCenter} Center and the required HQ building on pace. Run ${progress.workerCount} construction queues.`} button="Open Growth Lab" onClick={()=>onOpen('growth')}/>
  <Action title="Research" status={`${progress.techCenterCount} tech center${progress.techCenterCount===1?'':'s'} active`} text="Keep Tech Center 1 on the T10 dependency path; use Tech Center 2 for parallel combat value." button="Plan research" onClick={()=>onOpen('growth')}/>
  <Action title="Heroes" status={namedHeroes?`${namedHeroes}/5 heroes configured`:'Setup required'} text={namedHeroes?'Concentrate XP, shards and skill medals on the primary squad.':'Enter your primary squad to calculate development order.'} button="Open Hero Lab" onClick={()=>onOpen('heroes')}/>
  <Action title="Drone" status={droneLevel?`Level ${droneLevel} · Boost ${boost}`:'Setup required'} text={droneLevel?'Push the next skill milestone and balance the weakest of six components.':'Add drone level, components, Combat Boost and chips.'} button="Open Drone Lab" onClick={()=>onOpen('drone')}/>
  <Action title="Gear" status={gearEntered?'Primary squad recorded':'Setup required'} text={gearEntered?'Fund attacker damage gear and defender survival gear first.':'Enter all four gear pieces for your five main heroes.'} button="Open Gear Lab" onClick={()=>onOpen('gear')}/>
  <Action title="Battle intelligence" status="1 analysis per week" text="Upload up to five battle-report screenshots for a focused AI improvement plan." button="Analyze a report" onClick={()=>onOpen('reports')}/>
 </div></section></>;
}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <div className="rounded-2xl border border-[#34233f] bg-[#110d16] p-5"><p className="text-[10px] font-black uppercase tracking-[.15em] text-[#927f9d]">{label}</p><p className="mt-3 text-3xl font-black">{value}</p><p className="mt-2 text-xs text-[#f078d0]">{note}</p></div>}
function Action({title,status,text,button,onClick}:{title:string;status:string;text:string;button:string;onClick:()=>void}){return <article className="group rounded-3xl border border-[#352442] bg-[#110c17] p-5 transition hover:-translate-y-0.5 hover:border-[#8b3aa4]"><div className="flex items-start justify-between gap-3"><h3 className="text-lg font-black">{title}</h3><span className="h-2.5 w-2.5 shrink-0 rounded-full bg-[#ff4fc8] shadow-[0_0_14px_#ff4fc8]"/></div><p className="mt-2 text-xs font-black uppercase tracking-[.1em] text-[#c36fd0]">{status}</p><p className="mt-3 min-h-12 text-sm leading-6 text-[#a99bb1]">{text}</p><button onClick={onClick} className="mt-5 text-xs font-black text-[#ff68d1]">{button} →</button></article>}
