'use client';
import {useMemo,useState} from 'react';
const COMPONENTS=['Radar','Turbo Engine','External Armor','Thermal Scope','Fuel Cell','Airborne Missile'];
const MILESTONES=[30,50,70,90,110];
type Profile={level:number;components:number[];chips:number[];combatBoost:number;data:number;parts:number};
const num=(v:unknown,f:number)=>typeof v==='number'&&Number.isFinite(v)?v:f;
const list=(v:unknown,n:number)=>{const a=Array.isArray(v)?v:[];return Array.from({length:n},(_,i)=>num(a[i],1))};
export function DroneLab({initial}:{initial:Record<string,unknown>}){
 const [p,setP]=useState<Profile>(()=>({level:num(initial.level,1),components:list(initial.components,6),chips:list(initial.chips,4),combatBoost:num(initial.combatBoost,0),data:num(initial.data,0),parts:num(initial.parts,0)})); const [message,setMessage]=useState('');
 const next=MILESTONES.find(v=>v>p.level), weakComponent=p.components.indexOf(Math.min(...p.components)), weakChip=p.chips.indexOf(Math.min(...p.chips)); const sets=p.combatBoost>=300?3:p.combatBoost>=150?2:p.combatBoost>=10?1:0;
 const readiness=useMemo(()=>Math.min(100,Math.round(Math.min(p.level,110)/110*50+p.components.reduce((a,b)=>a+b,0)/2+p.chips.reduce((a,b)=>a+b,0)/2+p.combatBoost/30)),[p]);
 async function save(){const r=await fetch('/api/labs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'drone',profile:p})});setMessage(r.ok?'Drone profile saved.':'Could not save drone profile.')}
 function setArray(key:'components'|'chips',i:number,value:number){setP(x=>({...x,[key]:x[key].map((v,j)=>j===i?Math.max(1,value):v)}))}
 return <><p className="text-sm font-black text-[#59d7ff]">DRONE DEVELOPMENT LAB</p><h1 className="mt-2 text-4xl font-black tracking-[-.04em]">Build the whole drone—not just its level.</h1><p className="mt-3 max-w-3xl text-[#8690a7]">Track level, all six components, Combat Boost and the four chips in your active set.</p>
 <div className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Drone level" value={String(p.level)}/><Stat label="Next skill milestone" value={next?String(next):'110 reached'}/><Stat label="Combat Boost" value={String(p.combatBoost)}/><Stat label="Chip sets unlocked" value={`${sets}/3`}/></div>
 <div className="mt-6 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><section className="rounded-3xl border border-[#252c3d] bg-[#0f1420] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">My drone</h2><p className="mt-1 text-xs text-[#7f899f]">Readiness score: {readiness}/100</p></div><button onClick={save} className="w-full rounded-xl bg-[#168eb4] px-8 py-4 font-black sm:w-auto">SAVE DRONE</button></div>{message&&<p className="mt-3 text-sm text-[#66efb1]">{message}</p>}
 <div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Drone level" value={p.level} max={200} onChange={level=>setP(x=>({...x,level}))}/><Field label="Combat Boost" value={p.combatBoost} min={0} max={500} onChange={combatBoost=>setP(x=>({...x,combatBoost}))}/><Field label="Battle Data owned" value={p.data} min={0} max={9999999999} onChange={data=>setP(x=>({...x,data}))}/><Field label="Drone Parts owned" value={p.parts} min={0} max={999999999} onChange={parts=>setP(x=>({...x,parts}))}/></div>
 <div className="mt-7"><p className="text-xs font-black text-[#59d7ff]">SIX COMPONENTS</p><p className="mt-1 text-xs text-[#68728b]">Three identical components merge into one component of the next level.</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{p.components.map((v,i)=><Field key={COMPONENTS[i]} label={COMPONENTS[i]} value={v} max={20} onChange={n=>setArray('components',i,n)}/>)}</div></div>
 <div className="mt-7"><p className="text-xs font-black text-[#59d7ff]">ACTIVE SKILL-CHIP SET</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{p.chips.map((v,i)=><Field key={i} label={`Chip ${i+1}`} value={v} max={20} onChange={n=>setArray('chips',i,n)}/>)}</div></div></section>
 <aside className="self-start rounded-3xl border border-[#252c3d] bg-[#0f1420] p-5"><p className="text-xs font-black tracking-[.14em] text-[#68728b]">YOUR DRONE PRIORITIES</p><ol className="mt-4 space-y-3 text-sm"><Priority title={next?`1. Push drone level ${next}`:'1. Maintain level progress'} text={next?`${next-p.level} levels until the next skill and appearance upgrade. Spend Battle Data and Parts on Monday for Duel VS points.`:'All published skill milestones through 110 are complete.'}/><Priority title={`2. Raise ${COMPONENTS[weakComponent]}`} text={`Lowest component: level ${p.components[weakComponent]}. Open and merge component chests on Wednesday for Duel VS points.`}/><Priority title={`3. Combat Boost → ${p.combatBoost<10?10:p.combatBoost<150?150:p.combatBoost<300?300:'next level'}`} text={p.combatBoost<10?'Level 10 unlocks chip set 1.':p.combatBoost<150?'Level 150 unlocks chip set 2.':p.combatBoost<300?'Level 300 unlocks chip set 3.':'All three published chip-set slots are unlocked.'}/><Priority title={`4. Balance Chip ${weakChip+1}`} text="Keep your active main-squad chip set balanced; save scarce legendary crafting material for that squad."/></ol><div className="mt-4 rounded-xl border border-[#314436] bg-[#122019] p-3 text-xs leading-5 text-[#85dcae]">Components unlock at drone level 15. Combat Boost becomes available on server day 82. Exact per-level costs are not shown because the source has no verified cost table.</div></aside></div></>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-[#252c3d] bg-[#111722] p-5"><p className="text-xs text-[#68728b]">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>}
function Priority({title,text}:{title:string;text:string}){return <li className="rounded-xl bg-[#171d2b] p-3"><strong>{title}</strong><p className="mt-1 text-xs leading-5 text-[#8e98ae]">{text}</p></li>}
function Field({label,value,onChange,min=1,max}:{label:string;value:number;onChange:(value:number)=>void;min?:number;max:number}){return <label><span className="text-[11px] font-bold uppercase tracking-[.1em] text-[#6f7990]">{label}</span><div className="mt-2 flex items-center rounded-xl border border-[#30384a] bg-[#151b28] p-1"><button type="button" onClick={()=>onChange(Math.max(min,value-1))} className="h-10 w-10 rounded-lg bg-[#232b3b] text-xl font-black">−</button><input type="number" min={min} max={max} value={value} onChange={e=>onChange(Math.min(max,Math.max(min,Number(e.target.value)||min)))} className="min-w-0 flex-1 bg-transparent text-center font-black outline-none"/><button type="button" onClick={()=>onChange(Math.min(max,value+1))} className="h-10 w-10 rounded-lg bg-[#232b3b] text-xl font-black">+</button></div></label>}
