'use client';
import {useMemo,useState} from 'react';
import {HEROES} from '@/lib/game-data/hero-data';
const SLOTS=['Gun','Data Chip','Armor','Radar']; type Role='Attacker'|'Defender'|'Support'; type HeroGear={name:string;role:Role;levels:number[]}; type Profile={heroes:HeroGear[]};
function role(name:string):Role{const found=HEROES.find(hero=>hero.name===name);return found?.role==='dps'?'Attacker':found?.role==='tank'?'Defender':'Support'}
export function GearLab({initial,heroProfile,focus}:{initial:Record<string,unknown>;heroProfile:Record<string,unknown>;focus:'Tank'|'Air'|'Missile'}){
 const saved=(initial as Partial<Profile>).heroes??[]; const focusVehicle=focus==='Air'?'aircraft':focus.toLowerCase(); const selected=((heroProfile.heroes as Array<{name?:string}>|undefined)??[]).filter(hero=>hero.name&&HEROES.find(item=>item.name===hero.name)?.vehicle===focusVehicle).slice(0,5);
 const [p,setP]=useState<Profile>(()=>({heroes:selected.map((hero,index)=>{const prior=saved.find(item=>item.name===hero.name)??saved[index];return{name:hero.name!,role:role(hero.name!),levels:prior?.levels??[1,1,1,1]}})})); const [message,setMessage]=useState('');
 const priorities=useMemo(()=>p.heroes.flatMap((hero,heroIndex)=>hero.levels.map((level,slot)=>({hero,heroIndex,slot,level,weight:hero.role==='Attacker'?(slot<2?0:2):hero.role==='Defender'?(slot>1?0:2):1}))).sort((a,b)=>a.weight-b.weight||a.level-b.level).slice(0,5),[p]);
 function updateLevel(hero:number,slot:number,value:number){setP(x=>({...x,heroes:x.heroes.map((item,i)=>i===hero?{...item,levels:item.levels.map((v,j)=>j===slot?Math.max(0,Math.min(40,value)):v)}:item)}))} async function save(){const r=await fetch('/api/labs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'gear',profile:p})});setMessage(r.ok?'Gear profile saved.':'Could not save gear profile.')}
 if(!selected.length)return <><p className="text-sm font-black text-[#ff4fc8]">GEAR DEVELOPMENT LAB</p><h1 className="mt-2 text-4xl font-black">Hero setup required.</h1><div className="mt-6 rounded-3xl border border-[#4a2857] bg-[#100b17] p-8"><p className="text-[#b6a4be]">Choose and save your five {focus} heroes in Hero Lab first. Their names and combat roles will automatically appear here—no duplicate entry.</p></div></>;
 return <><p className="text-sm font-black text-[#ff4fc8]">GEAR DEVELOPMENT LAB · {focus.toUpperCase()} T1</p><h1 className="mt-2 text-4xl font-black tracking-[-.04em]">Gear follows your saved heroes.</h1><p className="mt-3 max-w-3xl text-[#a799bb]">Hero names and roles come directly from Hero Lab. You only enter each gear level; OOPZ applies the correct role-based priority.</p>
 <div className="mt-6 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><section className="rounded-3xl border border-[#3b2450] bg-[#100b17] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">Primary squad gear</h2><p className="mt-1 text-xs text-[#9a89a8]">Synced from Hero Lab · levels 0–40</p></div><button onClick={save} className="w-full rounded-xl bg-gradient-to-r from-[#a855f7] to-[#ec4899] px-8 py-4 font-black sm:w-auto">SAVE GEAR</button></div>{message&&<p className="mt-3 text-sm text-[#ff8fda]">{message}</p>}<div className="mt-5 space-y-3">{p.heroes.map((hero,i)=><div key={hero.name} className="rounded-2xl border border-[#2e203b] bg-[#17101f] p-4"><div className="flex items-center justify-between"><p className="font-black">{hero.name}</p><span className="rounded-full bg-[#2b1935] px-3 py-1 text-[10px] font-black text-[#e18ddd]">{hero.role}</span></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{hero.levels.map((level,slot)=><label key={SLOTS[slot]}><span className="text-[10px] font-bold uppercase text-[#8e7c9c]">{SLOTS[slot]}</span><input type="number" min="0" max="40" value={level} onChange={e=>updateLevel(i,slot,Number(e.target.value))} className="mt-1 w-full rounded-lg bg-[#251930] px-3 py-2 text-center font-black outline-none focus:ring-1 focus:ring-[#ec4899]"/></label>)}</div></div>)}</div></section>
 <aside className="self-start rounded-3xl border border-[#3b2450] bg-[#100b17] p-5"><p className="text-xs font-black tracking-[.14em] text-[#9d7caf]">AUTO GEAR PLAN</p><div className="mt-4 space-y-3">{priorities.map((item,index)=><div key={`${item.heroIndex}-${item.slot}`} className="rounded-xl bg-[#1b1224] p-3"><p className="font-black"><span className="text-[#ff4fc8]">{index+1}.</span> {item.hero.name}: {SLOTS[item.slot]} → {item.level+1}</p><p className="mt-1 text-xs text-[#a08fad]">{item.hero.role==='Attacker'?(item.slot<2?'Damage gear is first for this attacker.':'Secondary survival upgrade.'):(item.hero.role==='Defender'?(item.slot>1?'Survival gear is first for this defender.':'Secondary damage upgrade.'):'Keep support gear balanced.')}</p></div>)}</div></aside></div></>;
}
