'use client';
import {useMemo,useState} from 'react';
const SLOTS=['Gun','Data Chip','Armor','Radar'];
type HeroGear={name:string;role:'Attacker'|'Defender'|'Support';levels:number[]};
type Profile={heroes:HeroGear[]};
const blank=(index:number):HeroGear=>({name:`Hero ${index+1}`,role:index<3?'Attacker':'Defender',levels:[1,1,1,1]});
export function GearLab({initial}:{initial:Record<string,unknown>}){
 const seed=initial as Partial<Profile>; const [p,setP]=useState<Profile>({heroes:Array.from({length:5},(_,i)=>seed.heroes?.[i]??blank(i))}); const [message,setMessage]=useState('');
 const priorities=useMemo(()=>p.heroes.flatMap((hero,heroIndex)=>hero.levels.map((level,slot)=>({hero,heroIndex,slot,level,weight:hero.role==='Attacker'?(slot<2?0:2):(slot>1?0:2)}))).sort((a,b)=>a.weight-b.weight||a.level-b.level).slice(0,5),[p]);
 function updateHero(i:number,patch:Partial<HeroGear>){setP(x=>({...x,heroes:x.heroes.map((h,j)=>j===i?{...h,...patch}:h)}))} function updateLevel(hero:number,slot:number,value:number){updateHero(hero,{levels:p.heroes[hero].levels.map((v,i)=>i===slot?Math.max(0,Math.min(40,value)):v)})}
 async function save(){const r=await fetch('/api/labs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'gear',profile:p})});setMessage(r.ok?'Gear profile saved.':'Could not save gear profile.')}
 return <><p className="text-sm font-black text-[#ff4fc8]">GEAR DEVELOPMENT LAB</p><h1 className="mt-2 text-4xl font-black tracking-[-.04em]">Put every blueprint where it wins fights.</h1><p className="mt-3 max-w-3xl text-[#a799bb]">Record the four gear levels on your primary squad. OOPZ prioritizes damage gear for attackers and survival gear for defenders.</p>
 <div className="mt-6 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><section className="rounded-3xl border border-[#3b2450] bg-[#100b17] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">Primary squad gear</h2><p className="mt-1 text-xs text-[#9a89a8]">Enter gear levels from 0–40.</p></div><button onClick={save} className="w-full rounded-xl bg-gradient-to-r from-[#a855f7] to-[#ec4899] px-8 py-4 font-black shadow-[0_12px_30px_rgba(236,72,153,.22)] sm:w-auto">SAVE GEAR</button></div>{message&&<p className="mt-3 text-sm text-[#ff8fda]">{message}</p>}<div className="mt-5 space-y-3">{p.heroes.map((hero,i)=><div key={i} className="rounded-2xl border border-[#2e203b] bg-[#17101f] p-4"><div className="grid gap-3 sm:grid-cols-[1fr_.7fr]"><input aria-label={`Hero ${i+1} name`} value={hero.name} onChange={e=>updateHero(i,{name:e.target.value})} className="rounded-lg border border-[#3b2a49] bg-[#21162c] px-3 py-2 font-black outline-none focus:border-[#ec4899]"/><select aria-label={`${hero.name} role`} value={hero.role} onChange={e=>updateHero(i,{role:e.target.value as HeroGear['role']})} className="rounded-lg border border-[#3b2a49] bg-[#21162c] px-3 py-2"><option>Attacker</option><option>Defender</option><option>Support</option></select></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{hero.levels.map((level,slot)=><label key={SLOTS[slot]}><span className="text-[10px] font-bold uppercase text-[#8e7c9c]">{SLOTS[slot]}</span><input type="number" min="0" max="40" value={level} onChange={e=>updateLevel(i,slot,Number(e.target.value))} className="mt-1 w-full rounded-lg bg-[#251930] px-3 py-2 text-center font-black outline-none focus:ring-1 focus:ring-[#ec4899]"/></label>)}</div></div>)}</div></section>
 <aside className="self-start rounded-3xl border border-[#3b2450] bg-[#100b17] p-5"><p className="text-xs font-black tracking-[.14em] text-[#9d7caf]">NEXT GEAR MOVES</p><div className="mt-4 space-y-3">{priorities.map((item,index)=><div key={`${item.heroIndex}-${item.slot}`} className="rounded-xl bg-[#1b1224] p-3"><p className="font-black"><span className="text-[#ff4fc8]">{index+1}.</span> {item.hero.name}: {SLOTS[item.slot]} → {item.level+1}</p><p className="mt-1 text-xs text-[#a08fad]">{item.hero.role==='Attacker'?(item.slot<2?'Primary damage gear for an attacker.':'Keep defenses from falling too far behind.'):(item.slot>1?'Primary survival gear for a defender.':'Raise after core defensive gear.')}</p></div>)}</div><p className="mt-4 text-[11px] leading-5 text-[#786886]">This planner provides priority order. Exact ore, blueprint and upgrade costs need a verified game dataset before they can be calculated safely.</p></aside></div></>;
}
