'use client';

import { useEffect, useMemo, useState } from 'react';
import type { CommanderProgress } from '@/lib/commander-progress';
import { calculateT10 } from '@/lib/game-data/calculate-t10';
import { T10_TREE } from '@/lib/game-data/t10-tree';
import { calcT10PrereqCosts } from '@/lib/game-data/building-upgrade-costs';

function short(value: number) { return new Intl.NumberFormat('en', { notation:'compact', maximumFractionDigits:1 }).format(Math.max(0,value)); }
function days(hours: number) { return `${(hours/24).toFixed(hours < 240 ? 1 : 0)} days`; }
function parseCompact(raw:string) { const clean=raw.trim().replaceAll(',','').replaceAll(' ',''); const match=clean.match(/^(\d+(?:\.\d+)?)\s*([kmb])?$/i); if(!match)return null; const scale={k:1_000,m:1_000_000,b:1_000_000_000}[match[2]?.toLowerCase() as 'k'|'m'|'b']??1; return Math.round(Number(match[1])*scale); }
function displayCompact(value:number) { if(!value)return ''; if(value>=1_000_000_000)return `${Number((value/1_000_000_000).toFixed(2))}B`; if(value>=1_000_000)return `${Number((value/1_000_000).toFixed(2))}M`; if(value>=1_000)return `${Number((value/1_000).toFixed(1))}K`; return String(value); }
function LevelField({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}) { return <div><span className="text-[11px] font-bold uppercase tracking-[.12em] text-[#6f7990]">{label}</span><div className="mt-2 flex items-center rounded-xl border border-[#30384a] bg-[#151b28] p-1"><button type="button" onClick={()=>onChange(Math.max(1,value-1))} className="h-10 w-10 rounded-lg bg-[#232b3b] text-xl font-black">−</button><input aria-label={label} type="number" min="1" max="35" value={value} onChange={e=>onChange(Math.min(35,Math.max(1,Number(e.target.value)||1)))} className="min-w-0 flex-1 bg-transparent text-center text-xl font-black outline-none"/><button type="button" onClick={()=>onChange(Math.min(35,value+1))} className="h-10 w-10 rounded-lg bg-[#232b3b] text-xl font-black">+</button></div></div>; }
function CompactField({label,value,onChange,valor=false}:{label:string;value:number;onChange:(value:number)=>void;valor?:boolean}) { const [draft,setDraft]=useState(displayCompact(value)); useEffect(()=>setDraft(displayCompact(value)),[value]); const steps=valor?[100,1_000,10_000]:[1_000_000,10_000_000,100_000_000,1_000_000_000]; return <div><div className="flex items-center justify-between"><span className="text-[11px] font-bold uppercase tracking-[.12em] text-[#6f7990]">{label}</span><span className="text-[10px] text-[#566077]">Use K, M or B</span></div><div className="relative mt-2"><input aria-label={label} inputMode="decimal" placeholder={valor?'e.g. 12.5K':'e.g. 740M or 1.3B'} value={draft} onChange={e=>{setDraft(e.target.value);const parsed=parseCompact(e.target.value);if(parsed!=null)onChange(parsed)}} onBlur={()=>setDraft(displayCompact(value))} className="w-full rounded-xl border border-[#30384a] bg-[#151b28] px-4 py-3 pr-20 text-lg font-black outline-none focus:border-[#7c5cff]"/><span className="absolute right-4 top-3.5 text-xs text-[#66efb1]">{short(value)}</span></div><div className="mt-2 flex flex-wrap gap-1.5">{steps.map(step=><button type="button" key={step} onClick={()=>onChange(value+step)} className="rounded-lg border border-[#30384a] bg-[#171d2b] px-2.5 py-1.5 text-[11px] font-bold text-[#aab2c4] hover:border-[#7c5cff]">+{short(step)}</button>)}<button type="button" onClick={()=>onChange(0)} className="rounded-lg px-2.5 py-1.5 text-[11px] font-bold text-[#ee8ca8]">Clear</button></div></div>; }
function SpeedField({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}) { return <div><div className="flex justify-between"><span className="text-[11px] font-bold uppercase tracking-[.12em] text-[#6f7990]">{label}</span><strong>{value}%</strong></div><input aria-label={label} type="range" min="0" max="500" step="5" value={value} onChange={e=>onChange(Number(e.target.value))} className="mt-3 w-full accent-[#7c5cff]"/><div className="mt-2 flex gap-1.5">{[0,50,100,150,200,300].map(preset=><button type="button" key={preset} onClick={()=>onChange(preset)} className={`rounded-lg px-2 py-1 text-[10px] font-bold ${value===preset?'bg-[#7c5cff]':'bg-[#171d2b] text-[#8e98ae]'}`}>{preset}%</button>)}</div></div>; }

type LeagueRow = { playerName:string; hqLevel:number; techCenterLevel:number; barracksLevel:number; researchSpeed:number; techProgress:Record<string,number>; updatedAt:number };
export function GrowthPlanner({initial,league}:{initial:CommanderProgress;league:LeagueRow[]}) {
  const [profile,setProfile]=useState(initial); const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false);
  const research=useMemo(()=>calculateT10(profile.techProgress),[profile.techProgress]);
  const buildings=useMemo(()=>calcT10PrereqCosts(profile.hqLevel,profile.techCenterLevel,profile.barracksLevel),[profile.hqLevel,profile.techCenterLevel,profile.barracksLevel]);
  const researchHours=research.total.time/(1+profile.researchSpeed/100); const buildingHours=buildings.combined.timeHours/(1+profile.constructionSpeed/100);
  const nodes=Object.values(T10_TREE); const totalLevels=nodes.reduce((sum,node)=>sum+node.levels.length,0); const doneLevels=nodes.reduce((sum,node)=>sum+Math.min(node.levels.length,profile.techProgress[node.id]??0),0);
  const available=nodes.filter(node=>(profile.techProgress[node.id]??0)<node.levels.length && (node.requires??[]).every(id=>(profile.techProgress[id]??0)>=T10_TREE[id].levels.length)).slice(0,4);
  const resourceRows=[['Food',research.total.food+buildings.combined.food,profile.food],['Iron',research.total.iron+buildings.combined.iron,profile.iron],['Gold',research.total.gold+buildings.combined.gold,profile.gold],['Valor',research.total.valor,profile.valor]] as const;
  async function save(){setSaving(true);setMessage('');const response=await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)});setMessage(response.ok?'Profile saved. Your plan is now remembered.':'Could not save your profile.');setSaving(false);}
  return <><p className="text-sm font-black text-[#8d75ff]">GROWTH & TECH LAB</p><h1 className="mt-2 text-4xl font-black tracking-[-.04em]">Your shortest path to the next power spike.</h1><p className="mt-3 max-w-3xl text-[#8690a7]">Enter what you actually own. OOPZ calculates your remaining T10 buildings, research nodes, resources, time and immediate next actions from the AMP game dataset.</p>
    <div className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl border border-[#252c3d] bg-[#111722] p-5"><p className="text-xs text-[#68728b]">T10 research</p><p className="mt-3 text-3xl font-black">{Math.round(doneLevels/totalLevels*100)}%</p><p className="mt-2 text-xs text-[#66efb1]">{doneLevels}/{totalLevels} node levels</p></div><div className="rounded-2xl border border-[#252c3d] bg-[#111722] p-5"><p className="text-xs text-[#68728b]">Building gates</p><p className="mt-3 text-3xl font-black">{buildings.combined.levelsNeeded}</p><p className="mt-2 text-xs text-[#66efb1]">Levels remaining to HQ/TC/Barracks 30</p></div><div className="rounded-2xl border border-[#252c3d] bg-[#111722] p-5"><p className="text-xs text-[#68728b]">Research time</p><p className="mt-3 text-3xl font-black">{days(researchHours)}</p><p className="mt-2 text-xs text-[#66efb1]">With your research-speed bonus</p></div><div className="rounded-2xl border border-[#252c3d] bg-[#111722] p-5"><p className="text-xs text-[#68728b]">Gold still needed</p><p className="mt-3 text-3xl font-black">{short(Math.max(0,research.total.gold+buildings.combined.gold-profile.gold))}</p><p className="mt-2 text-xs text-[#66efb1]">After current inventory</p></div></div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[.95fr_1.05fr]"><section className="rounded-3xl border border-[#252c3d] bg-[#0f1420] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">My account</h2><p className="mt-1 text-xs text-[#7f899f]">Type game-style values such as 740M or 1.3B.</p></div><button onClick={save} disabled={saving} className="rounded-xl bg-[#7c5cff] px-5 py-3 text-sm font-black disabled:opacity-50">{saving?'Saving…':'Save profile'}</button></div>{message&&<p className="mt-3 rounded-lg bg-[#14261f] px-3 py-2 text-xs text-[#66efb1]">{message}</p>}<div className="mt-6"><p className="mb-3 text-xs font-black tracking-[.13em] text-[#8d75ff]">BUILDINGS</p><div className="grid gap-3 sm:grid-cols-3"><LevelField label="HQ" value={profile.hqLevel} onChange={v=>setProfile(p=>({...p,hqLevel:v}))}/><LevelField label="Tech Center" value={profile.techCenterLevel} onChange={v=>setProfile(p=>({...p,techCenterLevel:v}))}/><LevelField label="Barracks" value={profile.barracksLevel} onChange={v=>setProfile(p=>({...p,barracksLevel:v}))}/></div></div><div className="mt-7"><p className="mb-3 text-xs font-black tracking-[.13em] text-[#8d75ff]">SPEED BONUSES</p><div className="grid gap-5 sm:grid-cols-2"><SpeedField label="Research speed" value={profile.researchSpeed} onChange={v=>setProfile(p=>({...p,researchSpeed:v}))}/><SpeedField label="Construction speed" value={profile.constructionSpeed} onChange={v=>setProfile(p=>({...p,constructionSpeed:v}))}/></div></div><div className="mt-7"><p className="mb-3 text-xs font-black tracking-[.13em] text-[#8d75ff]">CURRENT INVENTORY</p><div className="grid gap-5 sm:grid-cols-2"><CompactField label="Food" value={profile.food} onChange={v=>setProfile(p=>({...p,food:v}))}/><CompactField label="Iron" value={profile.iron} onChange={v=>setProfile(p=>({...p,iron:v}))}/><CompactField label="Gold" value={profile.gold} onChange={v=>setProfile(p=>({...p,gold:v}))}/><CompactField label="Valor badges" valor value={profile.valor} onChange={v=>setProfile(p=>({...p,valor:v}))}/></div></div></section>
    <section className="rounded-3xl border border-[#252c3d] bg-[#0f1420] p-6"><p className="text-xs font-black tracking-[.15em] text-[#68728b]">YOUR NEXT MOVES</p><div className="mt-5 space-y-3">{buildings.combined.levelsNeeded>0&&<div className="rounded-xl bg-[#171d2b] p-4"><p className="font-black">1. Clear the building gate</p><p className="mt-1 text-sm text-[#8e98ae]">HQ {profile.hqLevel}/30 · Tech Center {profile.techCenterLevel}/30 · Barracks {profile.barracksLevel}/30</p><p className="mt-2 text-xs text-[#e2c477]">Estimated build time: {days(buildingHours)}</p></div>}{available.map((node,index)=><div key={node.id} className="rounded-xl bg-[#171d2b] p-4"><p className="font-black">{index+1+(buildings.combined.levelsNeeded?1:0)}. {node.name} → level {(profile.techProgress[node.id]??0)+1}</p><p className="mt-1 text-xs text-[#66efb1]">Available now on the dependency path</p></div>)}{!available.length&&doneLevels===totalLevels&&<p className="rounded-xl bg-[#14261f] p-4 font-black text-[#66efb1]">Unit X path complete. T10 unlocked.</p>}</div></section></div>
    <section className="mt-6 rounded-3xl border border-[#252c3d] bg-[#0f1420] p-6"><h2 className="text-xl font-black">Remaining cost</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{resourceRows.map(([label,total,owned])=><div key={label} className="rounded-xl bg-[#151b28] p-4"><p className="text-xs text-[#6f7990]">{label}</p><p className="mt-2 text-xl font-black">{short(Math.max(0,total-owned))}</p><p className="mt-1 text-[11px] text-[#8b95aa]">{short(total)} total · {short(owned)} owned</p></div>)}</div></section>
    <section className="mt-6 rounded-3xl border border-[#252c3d] bg-[#0f1420] p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-black">Special Forces / T10 nodes</h2><p className="mt-1 text-sm text-[#7f899f]">Set each node to the level currently completed in-game.</p></div><p className="text-xs text-[#e2c477]">Costs are planning estimates from AMP’s collected game data.</p></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{nodes.map(node=>{const level=profile.techProgress[node.id]??0;return <label key={node.id} className="rounded-xl border border-[#252c3d] bg-[#151b28] p-4"><span className="flex justify-between gap-3 text-sm font-black"><span>{node.name}</span><span className="text-[#8d75ff]">{level}/{node.levels.length}</span></span><input aria-label={`${node.name} completed level`} type="range" min="0" max={node.levels.length} value={level} onChange={e=>setProfile(p=>({...p,techProgress:{...p.techProgress,[node.id]:Number(e.target.value)}}))} className="mt-4 w-full accent-[#7c5cff]" /></label>})}</div></section>
    <section className="mt-6 overflow-hidden rounded-3xl border border-[#252c3d] bg-[#0f1420]"><div className="p-6"><h2 className="text-xl font-black">Alliance growth comparison</h2><p className="mt-2 text-sm text-[#7f899f]">Only verified commanders who saved a profile appear here. Use it to find peers and mentors—not to shame progress.</p></div><div className="overflow-auto"><table className="w-full min-w-[720px] text-left"><thead className="border-y border-[#252c3d] text-[11px] uppercase tracking-[.12em] text-[#68728b]"><tr><th className="p-4">Commander</th><th>HQ</th><th>Tech Center</th><th>Barracks</th><th>T10 path</th><th>Research speed</th><th>Updated</th></tr></thead><tbody>{league.map(row=>{const completed=nodes.reduce((sum,node)=>sum+Math.min(node.levels.length,row.techProgress[node.id]??0),0);return <tr key={row.playerName} className="border-b border-[#1e2432]"><td className="p-4 font-black">{row.playerName}</td><td>{row.hqLevel}</td><td>{row.techCenterLevel}</td><td>{row.barracksLevel}</td><td>{Math.round(completed/totalLevels*100)}%</td><td>{row.researchSpeed}%</td><td className="text-xs text-[#7f899f]">{new Date(row.updatedAt).toLocaleDateString()}</td></tr>})}{!league.length&&<tr><td colSpan={7} className="p-8 text-center text-[#7f899f]">No commander profiles saved yet. Be the first.</td></tr>}</tbody></table></div></section></>;
}
